#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/lib/zsh-namedir/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/lib/zsh-namedir/init.zsh"
fi

. `brew --prefix`/etc/profile.d/z.sh

# Who doesn't want home and end to work?

# Skip forward/back a word with opt-arrow
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

# Skip to start/end of line with cmd-arrow
bindkey '[E' beginning-of-line
bindkey '[F' end-of-line

# Delete word with opt-backspace/opt-delete
bindkey '[G' backward-kill-word
bindkey '[H' kill-word

# Delete line with cmd-backspace
bindkey '[I' kill-whole-line

alias t=trash
alias rm=trash

alias artisan='php artisan'

alias phpserve='php -S localhost:7999'
alias showfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder'
